# ===================================================================
# Configuracion de Servidor y Aplicacion VideoRent
# ===================================================================
server.port=8080
spring.application.name=videorent-backend

# ===================================================================
# Conexion a Microsoft SQL Server (SSMS)
# Ajuste las credenciales segun la configuracion de su instancia local
# ===================================================================
spring.datasource.url=jdbc:sqlserver://163.178.173.130;databaseName=VideoRent_A42415_II2026;encrypt=true;trustServerCertificate=true;
spring.datasource.username=Lenguajes
spring.datasource.password=lenguajesparaiso2025
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#context path
server.servlet.context-path=/renting
server.port=8084

# ===================================================================
# Configuracion de JPA e Hibernate Internals
# ===================================================================
# Mantiene las tablas existentes creadas mediante script SQL Server
spring.jpa.hibernate.ddl-auto=update

# Mostrar sentencias SQL ejecutadas en la consola para depuracion
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto para Microsoft SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ===================================================================
# Configuracion de OpenAPI / Swagger UI
# ===================================================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
